version: '3'

services:
  web:
    container_name: "web"
    image: nginx:alpine
    depends_on:
      - api
    ports:
      - "8082:81"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d

  api:
    container_name: api
    build: .
    volumes:
      - .:/api
    restart: always
    env_file:
      - config\docker.env
    depends_on:
      - mongo

  mongo:
    image: mongo
    restart: always
    env_file:
      - config\docker.env
    environment:
      MONGO_INITDB_ROOT_USERNAME: $MONGODB_ADMINUSERNAME
      MONGO_INITDB_ROOT_PASSWORD: $MONGODB_ADMINPASSWORD
    ports:
      - "27017:27017"

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    env_file:
      - config\docker.env
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: $MONGODB_ADMINUSERNAME
      ME_CONFIG_MONGODB_ADMINPASSWORD: $MONGODB_ADMINPASSWORD
      ME_CONFIG_MONGODB_URL: $MONGODB_URL
    depends_on:
      - mongo
    