version: '3'

services:
  web:
    container_name: "web"
    image: nginx:alpine
    depends_on:
      - api
    ports:
      - "8082:81"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d

  api:
    container_name: api
    build: .
    volumes:
      - .:/api
    restart: always
    depends_on:
      - mongo
    env_file:
      - config\docker.env

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: $MONGO_USERNAME
      MONGO_INITDB_ROOT_PASSWORD: $MONGO_PASSWORD
    ports:
      - "27017:27017"
    env_file:
      - config\docker.env

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: $MONGO_USERNAME
      ME_CONFIG_MONGODB_ADMINPASSWORD: $MONGO_PASSWORD
      ME_CONFIG_MONGODB_URL: mongodb://$MONGO_USERNAME:$MONGO_PASSWORD@$MONGO_HOST:$MONGO_PORT
    depends_on:
      - mongo
    env_file:
      - config\docker.env